// Team members data
export const teamMembers = [
  {
    id: "gia",
    name: "Gia Minh Hua",
    initials: "GH",
    role: "CEO / Lead Software Developer",
    about:
      "Gia is a Computer Science major at Cal Poly Pomona. He has a strong passion in building application and has been doing since high school. He specializes in C++, Java, Python, and React. Gia leads our technical team and ensures that all projects meet the highest quality standards.",
    skills: ["C++", "Java", "Python", ],
    bgColor: "bg-blue-100",
    textColor: "text-blue-800",
  },
  {
    id: "thu",
    name: "Thu Nguyen",
    initials: "TN",
    role: "Backend Developer",
    about:
      "She is a Computer Science major with a minor in Data Science, passionate about exploring the data-driven technologies. She is most familiar with Python and its libraries, which she uses for programming and building solutions to problems. She is also eager to dive deeper into the fields of Machine Learning and Data Science, with the goal of applying these skills to solve real-world challenges and uncover meaningful insights from data.",
    skills: ["Python", "Java", "C++", "SQL"],
    bgColor: "bg-purple-100",
    textColor: "text-purple-800",
  },
  {
    id: "an",
    name: "An Nguyen",
    initials: "AN",
    role: "Frontend Developer",
    about:
      "He is a Computer Science major at Cal Poly Pomona, passionate about blending creativity and technology through projects like game development with Godot, music-tech experiments with piano, and applying machine learning with computer vision to enhance musical experiences. Aspiring to become a skilled software engineer while exploring how technology can make a real-world impact.",
    skills: ["Python", "Java", "C++", "gdscript"],
    bgColor: "bg-green-100",
    textColor: "text-green-800",
  },
  {
    id: "nicholas",
    name: "Nicholas Perez",
    initials: "NP",
    role: "Frontend Developer",
    about:
      "Nicholas is a Computer Science Major with a Minor in Data Science. He enjoys creating projects that merge Data Science and Web Development, focusing on building dynamic and visually compelling user experiences. Specializing in Python, Next.js, and TypeScript, he leverages Tailwind CSS to craft responsive and polished designs. He is passionate about developing web applications that not only look great but also present complex data in an intuitive and interactive way, empowering users to explore and understand insights effectively.",
    skills: ["Python", "NextJS", "Typescript", "Tailwind CSS"],
    bgColor: "bg-yellow-100",
    textColor: "text-yellow-800",
  },
  {
    id: "viet",
    name: "Viet Tran",
    initials: "VT",
    role: "Backend Developer",
    about:
      "Viet is a Computer Science major with experience in Python, HTML, and CSS. He likes to explore and learn about Machine Learning and AI. He also enjoys building interactive web applications, creating solutions that improve everyday life, and solving real-world problems.",
    skills: ["HTML", "CSS", "Python"],
    bgColor: "bg-pink-100",
    textColor: "text-pink-800",
  },
];

// Meeting logs
export const logs = [
  {
    id: "meeting59",
    title: "Mobile Display Fixes",
    desc: "Reviewed issues on mobile screens and updated layouts to improve the mobile experience.",
    date: "November 26, 2025 • 7:00 PM - 8:00 PM",
  },
  {
    id: "meeting58",
    title: "Messaging System",
    desc: "Discussed how the messaging system should work and finished the basic chat and conversation features.",
    date: "November 25, 2025 • 8:00 PM - 10:00 PM",
  },
  {
    id: "meeting57",
    title: "Search bar Update",
    desc: "Talked about improving the search bar, included searchbar in home page and added filters for ingredients, and categories.",
    date: "November 24, 2025 • 7:30 PM - 9:00 PM",
  },
  {
    id: "meeting56",
    title: "Favorites for User Recipes",
    desc: "Added the ability to favorite recipes created by users.",
    date: "November 22, 2025 • 7:00 PM - 8:00 PM",
  },
  {
    id: "meeting55",
    title: "Homepage Redesign",
    desc: "Redesigned the homepage to show user-created recipes more clearly.",
    date: "November 21, 2025 • 8:00 PM - 10:00 PM",
  },
  {
    id: "meeting54",
    title: "Recipe Rating Feature",
    desc: "Added a simple star rating system for recipes.",
    date: "November 20, 2025 • 7:30 PM - 9:00 PM",
  },
  {
    id: "meeting53",
    title: "Friend List Feature",
    desc: "Added a friend list so users can see the friends they have added.",
    date: "November 18, 2025 • 8:00 PM - 9:00 PM",
  },
  {
    id: "meeting52",
    title: "Explore Searchbar",
    desc: "Added a simple search bar for explore recipe.",
    date: "November 17, 2025 • 7:00 PM - 8:00 PM",
  },
  {
    id: "meeting51",
    title: "Recipe Comments",
    desc: "Added a comment section inside the recipe popup.",
    date: "November 16, 2025 • 8:00 PM - 9:30 PM",
  },
  {
    id: "meeting50",
    title: "Unfriend Feature",
    desc: "Added an option to remove friends with a simple confirmation step.",
    date: "November 14, 2025 • 7:00 PM - 8:00 PM",
  },
  {
    id: "meeting49",
    title: "Notification Fixes",
    desc: "Reviewed notification issues and made updates to improve how friend request notifications work.",
    date: "November 13, 2025 • 7:00 PM - 8:30 PM",
  },
  {
    id: "meeting48",
    title: "Other User Profile Page",
    desc: "Created others profile page to view other profile.",
    date: "November 11, 2025 • 8:00 PM - 9:00 PM",
  },
  {
    id: "meeting47",
    title: "Friend & Notification Models",
    desc: "Discussed how to store friends and notifications in the database and updated the models.",
    date: "November 10, 2025 • 7:30 PM - 9:00 PM",
  },
  {
    id: "meeting46",
    title: "Favorites UI Update",
    desc: "Improved the favorite button and added a small confirmation popup.",
    date: "November 8, 2025 • 7:00 PM - 8:00 PM",
  },
  {
    id: "meeting45",
    title: "Community Page",
    desc: "Discussed the design for the Community page and built the page to show users and send friend requests.",
    date: "November 7, 2025 • 8:00 PM - 10:00 PM",
  },
  {
    id: "meeting44",
    title: "Avatar Save",
    desc: "Made user avatars save to the database so they no longer reset after login.",
    date: "November 5, 2025 • 7:00 PM - 8:30 PM",
  },
  {
    id: "meeting43",
    title: "Favorite API Work",
    desc: "Connected the favorite API and displayed the users favorited recipes.",
    date: "November 4, 2025 • 7:00 PM - 8:00 PM",
  },
  {
    id: "meeting42",
    title: "Instructions & Video URL",
    desc: "Added fields for recipe instructions and an optional video link.",
    date: "November 2, 2025 • 8:00 PM - 9:00 PM",
  },
  {
    id: "meeting41",
    title: "Ingredients & Categories",
    desc: "Added ingredients and category options to the recipe creation form.",
    date: "November 1, 2025 • 7:30 PM - 8:30 PM",
  },
  {
    id: "meeting40",
    title: "AWS Photo Upload",
    desc: "Added support for uploading recipe photos using AWS.",
    date: "October 30, 2025 • 8:00 PM - 9:30 PM",
  },
  {
    id: "meeting39",
    title: "Recipe Video Embed Fix",
    desc: "Fixed the video in the recipe popup so it plays inside the popup instead of opening a new tab.",
    date: "October 29, 2025 • 7:00 PM - 8:00 PM",
  },
  {
    id: "meeting38",
    title: "Research and Idea Exploration",
    desc: "Researched new ideas and explored design inspirations for upcoming features and improvements.",
    date: "October 27, 2025 • 7:00 PM - 8:30 PM",
  },
  {
    id: "meeting37",
    title: "Next Deliverables Discussion",
    desc: "Discussed the next deliverables and defined priorities for upcoming development stages.",
    date: "October 26, 2025 • 8:00 PM - 9:00 PM",
  },
  {
    id: "meeting36",
    title: "Architecture Document Finalization",
    desc: "Finalized the architecture design document, ensuring consistency across all sections.",
    date: "October 24, 2025 • 8:00 PM - 9:30 PM",
  },
  {
    id: "meeting35",
    title: "Architecture Design Adjustments",
    desc: "Adjusted the architecture design document based on team feedback and recent updates.",
    date: "October 23, 2025 • 7:30 PM - 9:00 PM",
  },
  {
    id: "meeting34",
    title: "Progress Review Meeting",
    desc: "Met to review current progress and discuss completed tasks and challenges.",
    date: "October 21, 2025 • 8:00 PM - 9:00 PM",
  },
  {
    id: "meeting33",
    title: "Task Allocation for New Features",
    desc: "Decided who will work on each part: create recipe popup, recipe interaction, and change password features.",
    date: "October 19, 2025 • 7:00 PM - 8:00 PM",
  },
  {
    id: "meeting32",
    title: "Recipe Feature Brainstorm",
    desc: "Brainstormed ideas for the 'Create Recipe' popup, recipe interaction, and change password functionality.",
    date: "October 18, 2025 • 8:00 PM - 9:00 PM",
  },
  {
    id: "meeting31",
    title: "Architecture Design Draft",
    desc: "Created the initial draft for the system's architecture design.",
    date: "October 16, 2025 • 9:00 PM - 10:00 PM",
  },
  {
    id: "meeting30",
    title: "Front-End Adjustments",
    desc: "Made adjustments to the front-end components in the user customization feature.",
    date: "October 15, 2025 • 8:00 PM - 9:00 PM",
  },
  {
    id: "meeting29",
    title: "Feature Draft Completion",
    desc: "Finished the draft for the user customization and food recipe cards features.",
    date: "October 14, 2025 • 6:00 PM - 8:00 PM",
  },
  {
    id: "meeting28",
    title: "UI Design Planning",
    desc: "Designed the UI for user profile customization and food recipe cards, and assigned tasks to team members.",
    date: "October 12, 2025 • 7:00 PM - 9:00 PM",
  },
  {
    id: "meeting27",
    title: "Next Deliverable Discussion",
    desc: "Discussed the next deliverable, including User Profile Customization and Food Recipe Cards on the landing page.",
    date: "October 11, 2025 • 8:00 PM - 9:00 PM",
  },
  {
    id: "meeting26",
    title: "Final Data Model & Company's Website Update",
    desc: "Completed the final version of the data model and updated project progress logs on the company website.",
    date: "October 9, 2025 • 3:00 PM - 7:00 PM",
  },
  {
    id: "meeting25",
    title: "Data Model Review",
    desc: "Discussed and refined the data model by deciding which components to keep or remove.",
    date: "October 8, 2025 • 12:00 PM - 12:50 PM",
  },
  {
    id: "meeting24",
    title: "Backend Role Assignment",
    desc: "Assigned responsibilities for developing the backend functions of login and signup.",
    date: "October 6, 2025 • 8:00 PM - 9:00 PM",
  },
  {
    id: "meeting23",
    title: "Data Model Draft",
    desc: "Created the first draft of the project’s data model for database structure and relationships.",
    date: "October 5, 2025 • 9:00 PM - 10:00 PM",
  },
  {
    id: "meeting22",
    title: "Forgot Password Feature",
    desc: "Added a 'Forgot Password' option to the login page interface.",
    date: "October 3, 2025 • 5:00 PM - 6:00 PM",
  },
  {
    id: "meeting21",
    title: "Frontend Development for Core Pages",
    desc: "Developed frontend interfaces for the login, welcome, and register pages, including basic user interaction.",
    date: "October 2, 2025 • 8:30 PM - 10:00 PM",
  },
  {
    id: "meeting20",
    title: "Team Discussion on Core Pages",
    desc: "Discussed the layout and functionality for the login page, welcome page, and registration feature.",
    date: "October 1, 2025 • 8:00 AM - 10:30 AM",
  },
  {
    id: "meeting19",
    title: "Information Table Button Implementation",
    desc: "Created a functional button on the web page to display an information table.",
    date: "September 30, 2025 • 7:00 PM - 9:00 PM",
  },
  {
    id: "meeting18",
    title: "Database Draft Creation",
    desc: "Designed and developed the initial draft of the project database structure.",
    date: "September 28, 2025 • 8:00 PM - 10:00 PM",
  },
  {
    id: "meeting17",
    title: "SRS Final Review",
    desc: "Split some sections into functional requirements. Reviewed the entire SRS document for submission.",
    date: "September 26, 2025 • 12:00 PM - 12:50 PM",
  },
  {
    id: "meeting16",
    title: "Verb and Noun Review",
    desc: "Underlined verb and noun in the project goal parts in the project proposal and the SRS document.",
    date: "September 24, 2025 • 12:00 PM - 12:50 PM",
  },
  {
    id: "meeting15",
    title: "Client Section & Requirements",
    desc: "Discussed ideas on the client section and details on the functional requirements section.",
    date: "September 22, 2025 • 12:00 PM - 12:50 PM",
  },
  {
    id: "meeting14",
    title: "SRS Draft Integration",
    desc: "Combined individual SRS drafts into a single document. Reviewed flow and consistency.",
    date: "September 19, 2025 • 7:00 PM - 8:00 PM",
  },
  {
    id: "meeting13",
    title: "Requirements Challenges",
    desc: "Discussed challenges with writing system requirements. Shared examples from research and agreed on revisions.",
    date: "September 18, 2025 • 7:00 PM - 7:45 PM",
  },
  {
    id: "meeting12",
    title: "Partial Draft Review",
    desc: "Reviewed partial drafts of the SRS. Each member explained what they had written so far.",
    date: "September 17, 2025 • 7:00 PM - 8:00 PM",
  },
  {
    id: "meeting11",
    title: "SRS Outline Planning",
    desc: "Reviewed the ideas, sketched an outline, and assigned responsibilities for each section of the SRS report.",
    date: "September 14, 2025 • 8:00 PM - 10:00 PM",
  },
  {
    id: "meeting10",
    title: "SRS Ideas Discussion",
    desc: "Discussed and researched ideas for the SRS report.",
    date: "September 13, 2025 • 8:00 PM - 9:00 PM",
  },
  {
    id: "meeting09",
    title: "SRS Reports Review",
    desc: "Reviewed the previous semester's SRS reports.",
    date: "September 12, 2025 • 12:00 AM - 12:50 AM",
  },
  {
    id: "meeting08",
    title: "Final Proposal Review Discussion",
    desc: "Discussed final review of proposal.",
    date: "September 11, 2025 • 7:00 PM - 8:00 PM",
  },
  {
    id: "meeting07",
    title: "Proposal Draft Review",
    desc: "Reviewed draft proposal sections together. Made edits and suggestions.",
    date: "September 8, 2025 • 7:00 PM - 7:45 PM",
  },
  {
    id: "meeting06",
    title: "Proposal Planning",
    desc: "Researched online examples, discussed the proposal structure, and sketched out main sections. Assigned responsibilities for each part of the proposal.",
    date: "September 6, 2025 • 7:00 PM - 10:00 PM",
  },
  {
    id: "meeting05",
    title: "Start working on Proposal",
    desc: "Create the project proposal, design the mockup of the web application",
    date: "September 5, 2025 • 12:00 PM - 12:50 PM",
  },
  {
    id: "meeting04",
    title: "Progress Check-in",
    desc: "Members explained what parts of the website they adjusted or researched, and identified areas needing more technical help.",
    date: "September 3, 2025 • 7:00 PM - 7:45 PM",
  },
  {
    id: "meeting03",
    title: "First Implementation Session",
    desc: "Built a basic staff page, project page, and meeting logs for the website.",
    date: "September 1, 2025 • 7:00 PM - 9:00 PM",
  },
  {
    id: "meeting02",
    title: "Feature Research Check-in",
    desc: "Quick check-in meeting. Members explained what features they researched for recipe-sharing platforms and noted which areas needed more detail.",
    date: "August 31, 2025 • 7:00 PM - 7:45 PM",
  },
  {
    id: "meeting01",
    title: "Project Concept Decision",
    desc: "Narrowed down project ideas. Decided on a food recipe platform as the main concept for the social networking site.",
    date: "August 30, 2025 • 7:00 PM - 8:00 PM",
  },
  {
    id: "meeting00",
    title: "Initial Project Setup",
    desc: "Create the skeleton of the web application and set up the initial project structure",
    date: "August 29, 2025 • 12:00 PM - 12:50 PM",
  },
];

// Project Progresses
export const progress = [
  {
    id: "progress1",
    num: 1,
    desc: "Create a skeleton for the project",
  },
  {
    id: "progress2",
    num: 2,
    desc: "Set up the environment",
  },
  {
    id: "progress3",
    num: 3,
    desc: "Connect to database",
  },
  {
    id: "progress4",
    num: 4,
    desc: "Host on Vercel",
  },
  {
    id: "progress5",
    num: 5,
    desc: "Create Sign Up, Sign In pages and let new users to register",
  },
  {
    id: "progress6",
    num: 6,
    desc: "Create food recipe cards in the Explore Recipe tab by pulling data from a food API",
  },
  {
    id: "progress7",
    num: 7,
    desc: "Allow users to customize their profiles",
  },
  {
    id: "progress8",
    num: 8,
    desc: "Users can click on recipe to see its content",
  },
  {
    id: "progress9",
    num: 9,
    desc: "Allow users to change password and create recipe",
  },
  {
    id: "progress10",
    num: 10,
    desc: "Update recipe creation with photos, ingredients, categories, and full recipe details",
  },
  {
    id: "progress11",
    num: 11,
    desc: "Add favorite system for saving and viewing favorite recipes",
  },
  {
    id: "progress12",
    num: 12,
    desc: "Add Community page for discovering users and sending friend requests",
  },
  {
    id: "progress13",
    num: 13,
    desc: "Add full friend system including notifications and friend list",
  },
  {
    id: "progress14",
    num: 14,
    desc: "Add public user profile page to view other users' profiles",
  },
  {
    id: "progress15",
    num: 15,
    desc: "Add comment system for recipes",
  },
  {
    id: "progress16",
    num: 16,
    desc: "Add advanced search system with filtering for exploring recipes, and user-created recipes",
  },
  {
    id: "progress17",
    num: 17,
    desc: "Add recipe rating system",
  },
  {
    id: "progress18",
    num: 18,
    desc: "Redesign homepage to show user-created recipes",
  },
  {
    id: "progress19",
    num: 19,
    desc: "Add messaging and conversation system",
  },
  {
    id: "progress20",
    num: 20,
    desc: "Update the application to work on mobile",
  },
];